### ISSUE TITLE
Ban rules

### ISSUE THREAD

**Issue by SergeyUshakov** [Dentacoin/DentaVox#1]
1st ban: 24 hours
2nd ban: 3 days
3rd ban: permanent ban
All this goes with an email

**Comment by YouPlusWe** [comment]
@SergeyUshakov and the trigger is 3 wrong answers or 3 rushed tests in the last 7 days, right?

**Comment by SergeyUshakov** [comment]
![untitled](https://user-images.githubusercontent.com/18186461/33018514-632af598-cdff-11e7-963f-591e0d7c7468.png)
We have to add a checkbox on this step: for users to be informed in advance that we want only high quality answers and therefore we have implemented smart manipulation-protection mechanisms. So they should stay focus in order to use the platform.

**Comment by SergeyUshakov** [comment]
Exactly

**Comment by YouPlusWe** [comment]
@SergeyUshakov Please provide text for the new checkbox.

**Comment by SergeyUshakov** [comment]
I here by agree to give only high quality answers, any manipulations will result in a ban

**Comment by YouPlusWe** [comment]
@SergeyUshakov That's done. On your end you should do the following:
- Edit the 2 new email tempalates ( Ban - temprary, Ban - permanent )
- Change the checkbox text ( the text key is page.questionnaire.iagree )
