### ISSUE TITLE
DentaVox Menus

### ISSUE THREAD

**Issue by DariaKer** [Dentacoin/DentaVox#13]
Please, rename/reorder DentaVox menu as follows:
![dvox-menu](https://user-images.githubusercontent.com/39304982/40117977-3a26b238-5921-11e8-964f-0d820c160e80.png)

and edit the Questionnaire list as follows:
![dvox-list](https://user-images.githubusercontent.com/39304982/40117999-4e45b476-5921-11e8-9071-38a968cc4cc1.PNG)

- Please also allow the admin to filter/order surveys by name, category, award, status, type, etc. (add down arrows to column titles :) )- so we can quickly search them.

**Comment by YouPlusWe** [comment]
Type / Status can't be split into 2 columns - each survey is either Hidden or one of the other statuses.
