### ISSUE TITLE
Questionnaire Page - Missing Descriptions + Small Changes

### ISSUE THREAD

**Issue by DariaKer** [Dentacoin/DentaVox#14]
Please, correct as described.

![surveys](https://user-images.githubusercontent.com/39304982/40163900-b929ab68-59c0-11e8-88e9-5cb150d4ff3f.PNG)

**Comment by YouPlusWe** [comment]
Descriptions visible only on active questionnaires.
Default sorting set to category - displays the questionnaires groupped by category.
All other sortings ignore categories and display a plain list.
