### ISSUE TITLE
"Scroll To Bottom" button in Edit Survey

### ISSUE THREAD

**Issue by DariaKer** [Dentacoin/DentaVox#29]
Alex, please add a quick "Scroll To Bottom" button (like the "Scroll To Top" already present) in the Edit Survey menu AND/OR find a smart way to quickly take admins to the "Add Question" section. With lengthy surveys like the new ones (Caries, Bruxism) you have to scroll down a lot until you reach that part. Thanks!

![scroll-down](https://user-images.githubusercontent.com/39304982/40918569-5a361a4e-680f-11e8-9dd5-acfa3e06f385.PNG)

**Comment by YouPlusWe** [comment]
Moved the Add Question form above the questions list.
